version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: Nginx01
    ports:
      - "80:80"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - /static:/static
    depends_on:
      - web
  web:
    build: .
    container_name: Django-Jiller
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn Jiller.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - ./src:/src
      - /static:/static
    expose:
      - "8000"


  db:
    image: postgres:latest
    container_name: Postgres01

  redis:
    image: redis:latest
    container_name: Redis01
    ports:
      - '6379:6379'

  rabbit:
    hostname: rabbit
    image: rabbitmq:3.6.0
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"
      - "15672:15672"

  celeryworker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A Jiller worker -l info
    volumes:
      - ./src:/src
    links:
      - rabbit
      - redis
      - db
    depends_on:
      - rabbit
